[package]
name = "scylla"
version = "0.1.0"
authors = ["Matt Butcher <matt.butcher@microsoft.com>"]
edition = "2018"

[dependencies]
kube = "0.6.0"
#kube = { git = "https://github.com/clux/kube-rs", rev = "2624341b8abc7b6cfaa3c9cb31db716db44d10e8" }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
failure = "0.1.5"
spectral = "0.6"
reqwest = "0.9"
log = "0.4"
env_logger = "0.6.1"

[dependencies.k8s-openapi]
version = "0.4.0"
features = ["v1_11"]