apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: componentinstances.core.oam.dev
  labels:
    app.kubernetes.io/part-of: core.oam.dev
spec:
  group: core.oam.dev
  versions:
    - name: v1alpha1
      served: true
      storage: true
  scope: Namespaced
  names:
    plural: componentinstances
    singular: componentinstance
    kind: ComponentInstance
    shortNames:
    - compinst
