
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "scylla.fullname" . }}
  labels:
{{ include "scylla.labels" . | indent 4 }}

{{ if .Values.enableRBAC }}
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "scylla.fullname" . }}
  labels:
{{ include "scylla.labels" . | indent 4 }}
rules:
- apiGroups: ["", "apps", "batch", "extensions", "core.hydra.io", "apiextensions.k8s.io"]
  resources: ["*"]
  verbs: ["*"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "scylla.fullname" . }}
  labels:
{{ include "scylla.labels" . | indent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ template "scylla.fullname" . }}
  namespace: default
roleRef:
  kind: ClusterRole
  name: {{ template "scylla.fullname" . }}
{{ end }}