apiVersion: core.hydra.io/v1alpha1
kind: OperationalConfiguration
metadata:
  name: first-app
spec:
  components:
  - name: nginx-component
    instanceName: first-app-nginx
    parameterValues:
      - name: poet
        value: Eliot
      - name: poem
        value: The Wasteland
    traits:
      - name: ingress
        parameterValues:
          - name: hostname
            value: example.com
          - name: path
            value: /