apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: applicationconfigurations.core.hydra.io
spec:
  group: core.hydra.io
  versions:
    - name: v1alpha1
      served: true
      storage: true
  scope: Namespaced
  names:
    plural: applicationconfigurations
    singular: applicationconfiguration
    kind: ApplicationConfiguration
    shortNames:
      - cfg
      - configuration
      - configurations
